### ISSUE TITLE
First Shimmer effect start slowly

### ISSUE THREAD

**Issue by laco-dev** [valentinilk/compose-shimmer#27]
Hi, I use library very well.

## Issue 
In generally, API respond about 1 ~ 2seconds. but ShimmerEffect animation wait 1.5seconds below
```kotlin
animationSpec = infiniteRepeatable(
    animation = tween(
        800,
        easing = LinearEasing,
        delayMillis = 1_500, // I can't change `delayMillis`. it is interval time.
    ),
    repeatMode = RepeatMode.Restart,
),
```
because of this, animation effect doesn't show at first time.
I hope to change start delay of first animation.

Thanks.

**Comment by valentinilk** [comment]
Thanks! Fixed it with 1.3.0

That was something that annoyed me as well. I changed the `defaultShimmerTheme` to use a custom animation spec instead, which is based on a `KeyframesSpec`.

Instead of adding the delay to the beginning of the animation, it will now be added end, if you use the newly introduced `shimmerSpec` or the existing default theme.
