### ISSUE TITLE
A simple way to change the animation time

### ISSUE THREAD

**Issue by PierreVieira** [valentinilk/compose-shimmer#4]
Would it be possible to develop something like passing the animation time in milliseconds like `.shimmer(time = 500)`?

**Comment by valentinilk** [comment]
It's been a while since you asked, but I just had a look. Seems like the necessary constructors are locked up quite well.

So I don't think I'll add something like the suggested `time` parameter to the library itself, but I could rearrange a bit of code to enable you to write it on your own.

I'll give you an update in a day or two. :)

**Comment by valentinilk** [comment]
Just released version `v1.0.2`, which exposes the theming as a parameter for the `rememberShimmer` function. This will allow you to write a custom modifier, so you can extend it to fit your needs.

Please have a look at the new section in the readme:
[Custom Modifier](https://github.com/valentinilk/compose-shimmer#custom-modifier)
